easy_admin:
  site_name: 'KtopomozeSlovensku'
  entities:
    HelpRequest:
      class: App\Entity\HelpRequest
      label: Potrebujem Pomoc
      list:
        fields: ['id', 'createdAt', 'institutionName', 'contactPerson', 'telephone', 'email', 'address', 'requestText']
        sort: 'createdAt'
        actions: [{ name: 'export_dopyt', ask_confirm: false,type: 'route' }]
      show:
      search:
      new:
        fields:  ['institutionName', 'contactPerson', 'telephone', 'email', 'address', 'requestText']
    DonationItem:
      class: App\Entity\Item
      label: Typ pomôcky
      list:
        fields: ['id', 'name']
    DonationRequest:
      label: Darujem
      class: App\Entity\DonationRequest
      list:
        fields: ['id', 'createdAt', 'email', 'contactPerson', 'telephone', 'address',]
        actions: [{ name: 'export_ponuka', ask_confirm: false,type: 'route' }]
      new:
        fields: ['email','contactPerson', 'telephone', 'address']

  design:
    menu:
      - { entity: 'HelpRequest', icon: 'hands-helping'}
      - { entity: 'DonationRequest', icon: 'people-carry'}
      - { entity: 'DonationItem', icon: 'cubes'}

  user:
    display_name: true
    display_avatar: false

  edit:
    actions: ['show', '-delete']
  list:
    actions: ['show', 'search', 'edit', '-delete']
  show:
    actions: ['-edit', '-delete']
