easy_admin:
  site_name: 'KtopomozeSlovensku'
  entities:

    #
    # HelpRequest
    #
    HelpRequest:
      class: App\Entity\HelpRequest
      label: Potrebujem Pomoc
      list:
        fields: ['id', 'createdAt', 'resolved', 'institutionName', 'contactPerson', 'telephone', 'email', 'address', 'requestedText', 'requestedItems']
        sort: 'createdAt'
        actions: [{ name: 'export_dopyt', ask_confirm: false, type: 'route' }]
      show:
      search:
      new:
        fields:  ['institutionName', 'contactPerson', 'telephone', 'email', 'address', 'requestedItems']

    #
    # HelpRequestsItems
    #
    HelpRequestsItems:
      class: App\Entity\HelpRequestsItems
      label: Ziadane Prostriedky
      list:
        fields:
          - helpRequest
          - item
          - quantity
          - other
    #
    # DonationRequest
    #
    DonationRequest:
      label: Darujem
      class: App\Entity\DonationRequest
      list:
        fields: ['id', 'createdAt', 'resolved', 'email', 'contactPerson', 'telephone', 'address', 'donatedItems']
        sort: 'createdAt'
        actions: [{ name: 'export_ponuka', ask_confirm: false,type: 'route' }]
      new:
        fields: ['email','contactPerson', 'telephone', 'address']

    #
    # DonationRequestsItems
    #
    DonationRequestsItems:
      class: App\Entity\DonationRequestsItems
      label: Darovane Prostriedky
      list:
        fields:
          - item
          - donationRequest
          - quantity
          - other

    #
    # DonationItem
    #
    DonationItem:
      class: App\Entity\DonationItem
      label: Typ pomôcky
      list:
        fields: ['id', 'name', 'donations', 'donatedItems', 'requestedItems', 'show']
        actions: ['new', 'show', 'edit', 'delete']
      edit:
        fields:
          - 'name'
          - 'show'
      new:
        fields:
          - 'name'
          - 'show'

    #
    # Recipient
    #
    Recipient:
      class: App\Entity\Recipient
      label: 'Komu sme pomohli - prijemca'
      list:
        fields:
          - 'id'
          - 'institutionName'
          - 'donations'
          - 'recipientGroup'
        actions: ['show', 'edit', 'delete']
      show:
        fields: ['institutionName', 'donations', 'recipientGroup']
      edit:
        fields:
          - 'institutionName'
          - 'donations'
          - 'recipientGroup'

    #
    # Recipient Groups
    #
    RecipientGroup:
      class: App\Entity\RecipientGroup
      label: 'Komu sme pomohli - skupiny prijemcov'
      list:
        fields:
          - id
          - recipients
          - name
        actions: ['show', 'edit', 'delete']
      show:
        fields: ['recipients', 'name']
      edit:
        fields:
          - recipients
          - name
    #
    # Donation
    #
    Donation:
      class: App\Entity\Donation
      label: 'Komu sme pomohli - polozky'
      list:
        fields:
          - 'id'
          - recipient
          - donationItem
          - count
          - donatedAt
        actions: ['show', 'new', 'edit', 'delete']
      show:
        fields: ['recipient', 'donationItem', 'count']
        actions: ['edit', 'delete']
      edit:
        fields:
          - recipient
          - donationItem
          - count
          - donatedAt
        actions: ['-show', 'delete']
      new:
        fields:
          - recipient
          - donationItem
          - count
          - donatedAt

    #
    # Partner
    #
    Partner:
      class: App\Entity\Partner
      label: 'Partneri'
      list:
        fields: ['id', 'name', 'donatedAmount', 'nonFinacialHelp', 'helpedAt']
        actions: ['edit', 'delete', '-show']
      edit:
        fields: ['name', 'donatedAmount', 'nonFinacialHelp', 'helpedAt']
        actions: ['delete', '-show']

    AccountActualBalance:
      class: App\Entity\AccountActualBalance
      label: 'Aktuálny stav'
      list:
        fields: ['credit', 'debit', 'creditCount', 'debitCount', 'balance', 'balanceCount', 'updatedAt']
        actions: ['-new', '-edit', '-delete', 'show']
      show:
        fields: ['credit', 'debit', 'creditCount', 'debitCount', 'balance', 'balanceCount', 'updatedAt']
        actions: ['-new', '-edit', '-delete']

    AccountBalance:
      class: App\Entity\AccountBalance
      label: 'Po dňoch'
      list:
        fields: ['date', 'credit', 'debit', 'creditCount', 'debitCount', 'balance', 'balanceCount', 'createdAt', 'updatedAt']
        actions: ['-new', '-edit', '-delete', 'show']
      show:
        fields: ['date', 'credit', 'debit', 'creditCount', 'debitCount',  'balance', 'balanceCount', 'createdAt', 'updatedAt']
        actions: ['-new', '-edit', '-delete']

    AccountTransaction:
      class: App\Entity\AccountTransaction
      label: 'Transakcie'
      list:
        fields: ['id', 'date', 'credit', 'debit', 'transactionId', 'executionId', 'createdAt']
        actions: ['-new', '-edit', '-delete', 'show']
      show:
        fields: ['id', 'date', 'credit', 'debit', 'transactionId', 'executionId', 'createdAt']
        actions: ['-new', '-edit', '-delete']

  design:
    menu:
      - label: Žiadosti
        icon: hands-helping
        children:
          - { label: 'Zoznam', entity: HelpRequest, icon: 'list' }
          - { label: 'Žiadané prostriedky', entity: HelpRequestsItems, icon: 'cubes' }

      - label: Dary
        icon: people-carry
        children:
          - { label: 'Zoznam', entity: DonationRequest, icon: 'list' }
          - { label: 'Darovné prostriedky', entity: DonationRequestsItems, icon: 'cubes' }

      - label: 'Komu sme pomohli'
        icon: helicopter
        children:
          - { label: 'Prijemcovia', entity: Recipient, icon: 'users' }
          - { label: 'Skupiny príjemcov', entity: RecipientGroup, icon: 'tag' }
          - { label: 'Polozky', entity: Donation, icon: 'cubes' }

      - label: 'Web'
        icon: globe-europe
        children:
          - { entity: Partner, icon: 'handshake'}

      - label: 'Položky'
        icon: medkit
        entity: DonationItem

      - label: 'Príjmy/Výdaje'
        icon: 'money-bill'
        children:
          - { label: 'Aktuálny stav', entity: AccountActualBalance, icon: 'balance-scale' }
          - { label: 'Po dňoch', entity: AccountBalance, icon: 'calendar-alt' }
          - { label: 'Transakcie', entity: AccountTransaction, icon: 'list' }

  user:
    display_name: true
    display_avatar: false

  edit:
    actions: ['show', '-delete']
  list:
    actions: ['show', 'search', 'edit', '-delete']
    max_results: 50
  show:
    actions: ['-edit', '-delete']
