parameters:
  app.path.user_contracts: /admin/donations/imports

vich_uploader:
  db_driver: orm

  mappings:
    donation_imports:
      uri_prefix: '%app.path.user_contracts%'
      upload_destination: '%kernel.project_dir%/data/donations'
