version: '3.3'

services:
  ktopomozeslovensku-php:
    container_name: ktopomozeslovensku-php
    build: ./docker/php/
    working_dir: /srv/www
    depends_on:
      - ktopomozeslovensku-mysql
    environment:
      - USER_ID=${USER_ID:-1000}
      - USER_GROUP_ID=${USER_GROUP_ID:-1000}
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - PHP_DEV=true
    volumes:
      - ./:/srv/www:delegated
      - ~/.ssh:/var/www/.ssh
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  ktopomozeslovensku-php-xdebug:
    container_name: ktopomozeslovensku-php-xdebug
    build: ./docker/php/
    working_dir: /srv/www
    depends_on:
      - ktopomozeslovensku-mysql
    environment:
      - USER_ID=${USER_ID:-1000}
      - USER_GROUP_ID=${USER_GROUP_ID:-1000}
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - PHP_DEV_XDEBUG=true
      - PHP_DOCKER_HOST_IP=debug-pc.docker.pxfd.tech
      - XDEBUG_CONFIG=remote_host=debug-pc.docker.pxfd.tech idekey=xdebug
    volumes:
      - ./:/srv/www:delegated
      - ~/.ssh:/var/www/.ssh
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  ktopomozeslovensku-php-composer:
    build: ./docker/php-composer/
    container_name: ktopomozeslovensku-php-composer
    depends_on:
      - ktopomozeslovensku-mysql
    environment:
      - USER_ID=${USER_ID:-1000}
      - USER_GROUP_ID=${USER_GROUP_ID:-1000}
      - SYMFONY_ENV=dev
      - APP_ENV=dev
    volumes:
      - ./:/srv/www
      - ~/.ssh:/var/www/.ssh
    command: >
      bash -c "usermod -u ${USER_ID:-1000} www-data \
         && sudo -u www-data ssh-keyscan git.pixelfederation.com >> /var/www/.ssh/known_hosts \
         && sudo -u www-data composer dump-autoload --optimize --classmap-authoritative \
         && tail -f /dev/null"


  ktopomozeslovensku-mysql:
    container_name: ktopomozeslovensku-mysql
    image: mysql:8.0.16
    environment:
      MYSQL_ROOT_PASSWORD: Start@123
      MYSQL_USER: project
      MYSQL_DATABASE: project
      MYSQL_PASSWORD: Password1
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 33061:3306
    volumes:
      - mysql:/var/lib/mysql

  ktopomozeslovensku:
    container_name: ktopomozeslovensku-nginx
    image: nginx:latest
    ports:
    - 8888:80
    depends_on:
      - ktopomozeslovensku-php
      - ktopomozeslovensku-php-xdebug
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/srv/www:delegated


volumes:
  mysql: {}
