version: '3.3'

services:
  ktopomozeslovensku-php:
    container_name: ktopomozeslovensku-php
    build: ./docker/php/
    working_dir: /srv/www
    depends_on:
      - ktopomozeslovensku-mysql
    environment:
      - USER_ID=${USER_ID:-1000}
      - USER_GROUP_ID=${USER_GROUP_ID:-1000}
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - PHP_DEV=true
    volumes:
      - ./:/srv/www:delegated
      - ~/.ssh:/var/www/.ssh

  ktopomozeslovensku-mysql:
    container_name: ktopomozeslovensku-mysql
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_PASSWORD: Start@123
      MYSQL_USER: project
      MYSQL_DATABASE: project
      MYSQL_PASSWORD: Password1
    ports:
      - 33061:3306
    volumes:
      - mariadb:/var/lib/mysql

  ktopomozeslovensku:
    container_name: ktopomozeslovensku-nginx
    image: nginx:latest
    ports:
    - 8888:80
    depends_on:
      - ktopomozeslovensku-php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/srv/www:delegated


volumes:
  mariadb: {}
