version: 2
jobs:
  dev:
    docker:
      - image: circleci/php:7.3-node-browsers

    branches:
      only:
        - master
        - oldFroms_newDesign

    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn rsync
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: echo export HOST_PATH="${DEV_HOST_PATH}" >> $BASH_ENV
      - run: echo export DATABASE_URL="${DEV_DATABASE_URL}" >> $BASH_ENV
      - run: echo export APP_SECRET="${DEV_APP_SECRET}" >> $BASH_ENV
      - run: source $BASH_ENV

      - run: composer install -n --prefer-dist

      - run: rsync -avc -e 'ssh -p 13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l uid1953480' --exclude='.git' --exclude='.cache' --exclude='.composer' --delete . shellserver-3.websupport.sk:~/${HOST_PATH}
      - run: ssh -p13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uid1953480@shellserver-3.websupport.sk "rm -rf ~/${HOST_PATH}/var/cache/dev/*"

    requires:
      - build

  prod:
    docker:
      - image: circleci/php:7.3-node-browsers

    branches:
      only:
        - master

    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn rsync
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: echo export HOST_PATH="${PROD_HOST_PATH}" >> $BASH_ENV
      - run: echo export DATABASE_URL="${PROD_DATABASE_URL}" >> $BASH_ENV
      - run: echo export APP_SECRET="${PROD_APP_SECRET}" >> $BASH_ENV
      - run: source $BASH_ENV

      - run: composer install -n --prefer-dist

      # - run: rsync -avc -e 'ssh -p 13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l uid1953480' --exclude='.git' --exclude='.cache' --exclude='.composer' --delete . shellserver-3.websupport.sk:~/${HOST_PATH}
      # - run: ssh -p13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uid1953480@shellserver-3.websupport.sk "rm -rf ~/${HOST_PATH}/var/cache/prod/*"
workflows:
  version: 2
  ci-cd-deploy:
    jobs:
      - dev
      - hold:
          type: approval
          requires:
            - dev
      - prod:
          requires:
            - hold
