version: 2
jobs:
  dev:
    docker:
      - image: circleci/php:7.3-node-browsers

    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn rsync
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: echo export HOST_PATH="${DEV_HOST_PATH}" >> $BASH_ENV
      - run: source $BASH_ENV

      - run: echo APP_ENV=dev >> .env
      - run: echo APP_DEBUG=1 >> .env
      - run: echo DATABASE_URL="${DEV_DATABASE_URL}" >> .env
      - run: echo APP_SECRET="${DEV_APP_SECRET}" >> .env
      - run: echo ADMIN_PWD="${DEV_ADMIN_PWD}" >> .env
      - run: source .env

      - run: composer install -n --prefer-dist
      - run: ./bin/console doctrine:migrations:migrate -n

      - run: rsync -avc -e 'ssh -p 13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l uid1953480' --exclude='.git' --exclude='.cache' --exclude='.composer' --exclude='node_modules' --exclude='var' --delete . shellserver-3.websupport.sk:~/${HOST_PATH}
      - run: ssh -p13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uid1953480@shellserver-3.websupport.sk "mv ~/${HOST_PATH}/var/cache/dev ~/${HOST_PATH}/var/cache/dev_old;rm -rf ~/${HOST_PATH}/var/cache/dev_old"

  prod:
    docker:
      - image: circleci/php:7.3-node-browsers

    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn rsync
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: echo export HOST_PATH="${PROD_HOST_PATH}" >> $BASH_ENV
      - run: source $BASH_ENV

      - run: echo APP_ENV=prod >> .env
      - run: echo APP_DEBUG=0 >> .env
      - run: echo DATABASE_URL="${PROD_DATABASE_URL}" >> .env
      - run: echo APP_SECRET="${PROD_APP_SECRET}" >> .env
      - run: echo ADMIN_PWD="${PROD_ADMIN_PWD}" >> .env
      - run: source .env

      - run: composer install -n --prefer-dist
      - run: ./bin/console doctrine:migrations:migrate -n

      - run: rsync -avc -e 'ssh -p 13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l uid1953480' --exclude='.git' --exclude='.cache' --exclude='.composer' --exclude='node_modules' --exclude='var' --delete . shellserver-3.websupport.sk:~/${HOST_PATH}
      - run: ssh -p13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uid1953480@shellserver-3.websupport.sk "mv ~/${HOST_PATH}/var/cache/prod ~/${HOST_PATH}/var/cache/prod_old;rm -rf ~/${HOST_PATH}/var/cache/prod_old"
workflows:
  version: 2
  ci-cd-deploy:
    jobs:
      - dev
      - hold:
          type: approval
          requires:
            - dev
      - prod:
          requires:
            - hold
