version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          APP_ENV=prod

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      - run: composer install -n --prefer-dist

      - run: env
