version: 2
jobs:
  dev:
    docker:
      - image: circleci/php:7.3-node-browsers

    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      HOST_PATH: ${DEV_HOST_PATH}
      DATABASE_URL: ${DEV_DATABASE_URL}
      APP_SECRET: ${DEV_APP_SECRET}
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: composer install -n --prefer-dist
      - run: ls -la ~/.ssh/
      #- run: ssh-keyscan -H ${SFTP_HOST}:22 >> ~/.ssh/known_hosts
      - run: scp -P13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . uid1953480@shellserver-3.websupport.sk/${HOST_PATH}
      #- run: sshpass -p "${SFTP_PASS}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null rm ${HOST_PATH}var/cache/prod/*
      - run: ssh -p13322 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null uid1953480@shellserver-3.websupport.sk ls -la ${HOST_PATH}/var/cache/dev/*

    requires:
      - build

  prod:
    docker:
      - image: circleci/php:7.3-node-browsers

    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      HOST_PATH: ${PROD_HOST_PATH}
      DATABASE_URL: ${PROD_DATABASE_URL}
      APP_SECRET: ${PROD_APP_SECRET}
    steps:
      ## START GENERIC
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
      - run: sudo mkdir -p /usr/share/man/man1mkdir /usr/share/man/man1
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - run: sudo apt update && sudo apt install -y openssh-client sshpass nodejs ant git yarn
      - run: sudo docker-php-ext-install zip
      - run: touch .env
      ## END GENERIC

      - run: composer install -n --prefer-dist
      #- run: ssh-keyscan -H ${SFTP_HOST}:22 >> ~/.ssh/known_hosts
      #- run: sshpass -p "${SFTP_PASS}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null . ${SFTP_USER}@${SFTP_HOST}:22/${HOST_PATH}
      #- run: sshpass -p "${SFTP_PASS}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null rm ${HOST_PATH}var/cache/prod/*
      #- run: curl -k "sftp://${SFTP_HOST}:22/${HOST_PATH}" --user "${SFTP_USER}:${SFTP_PASS}" -T . --ftp-create-dirs
workflows:
  version: 2
  ci-cd-deploy:
    jobs:
      - dev
      - hold:
          type: approval
          requires:
            - dev
      - prod:
          requires:
            - hold
