home:
  methods: GET
  path: /
  controller: App\Controller\HomeController::index

about:
  methods: GET
  path: /o-projekte
  controller: App\Controller\AboutController::index

contact:
  methods: GET
  path: /kontakt
  controller: App\Controller\ContactController::index

donation:
  methods: GET
  path: /darujem
  controller: App\Controller\DonationController::index

donation_finance:
  methods: GET|POST
  path: /darujem-financnu-pomoc
  controller: App\Controller\DonationController::finance

donation_nonfinance:
  methods: GET|POST
  path: /darujem-nefinancnu-pomoc
  controller: App\Controller\DonationController::nonFinance

donation_success:
  methods: GET|POST
  path: /darujem/dakujeme
  controller: App\Controller\DonationController::success

export_dopyt:
  methods: GET
  path: /export/dopyt
  controller: App\Controller\ExportController::dopyt

export_ponuka:
  methods: GET
  path: /export/ponuka
  controller: App\Controller\ExportController::ponuka

help_request:
  methods: GET|POST
  path: /ziadost-o-pomoc
  controller: App\Controller\HelpRequestController::index

help_request_success:
  methods: GET
  path: /ziadost-o-pomoc/dakujeme
  controller: App\Controller\HelpRequestController::success

partners:
  methods: GET
  path: /garanti
  controller: App\Controller\PartnersController::index

policy:
  methods: GET
  path: /pravidla-ochrany-osobnych-udajov
  controller: App\Controller\PolicyController::index

recipients:
  methods: GET
  path: /komu-sme-pomohli
  controller: App\Controller\RecipientsController::index

speak-about-it:
  methods: GET
  path: /hovorme-o-tom
  controller: App\Controller\SpeakAboutItController::index

update_account_balance:
  methods: GET
  path: /update-account-balance/{cronToken}
  controller: App\Controller\UpdateAccountBalanceController::index
  requirements:
    cronToken: ^[0-9a-zA-Z]{64}

faq:
  methods: GET
  path: /faq
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: about
    permanent: true
