home:
  methods: GET
  path: /
  controller: App\Controller\HomeController::index

help_request:
  methods: GET|POST
  path: /ziadost-o-pomoc
  controller: App\Controller\HelpRequestController::index

help_request_success:
  methods: GET
  path: /ziadost-o-pomoc/dakujeme
  controller: App\Controller\HelpRequestController::success

recipients:
  methods: GET
  path: /komu-sme-pomohli
  controller: App\Controller\RecipientsController::index

faq:
  methods: GET
  path: /faq
  controller: App\Controller\FaqController::index

partners:
  methods: GET
  path: /garanti
  controller: App\Controller\PartnersController::index

policy:
  methods: GET
  path: /pravidla-ochrany-osobnych-udajov
  controller: App\Controller\PolicyController::index
