home:
  methods: GET
  path: /
  controller: App\Controller\HomeController::index

help_request:
  methods: GET|POST
  path: /ziadost-o-pomoc
  controller: App\Controller\HelpRequestController::index

recipients:
  methods: GET
  path: /komu-sme-pomohli
  controller: App\Controller\RecipientsController::index

faq:
  methods: GET
  path: /faq
  controller: App\Controller\FaqController::index

partners:
  methods: GET|
  path: /partneri
  controller: App\Controller\PartnersController::index
