home:
  methods: GET
  path: /
  controller: App\Controller\HomeController::index

about:
  methods: GET
  path: /o-projekte
  controller: App\Controller\AboutController::index

contact:
  methods: GET
  path: /kontakt
  controller: App\Controller\ContactController::index

donation:
  methods: GET
  path: /darujem
  controller: App\Controller\DonationController::index

donation_finance:
  methods: GET|POST
  path: /darujem-financnu-pomoc
  controller: App\Controller\DonationController::finance

donation_nonfinance:
  methods: GET|POST
  path: /darujem-nefinancnu-pomoc
  controller: App\Controller\DonationController::nonFinance

donation_success:
  methods: GET|POST
  path: /darujem/dakujeme
  controller: App\Controller\DonationController::success
  options:
    hide_in_sitemap: true

export_dopyt:
  methods: GET
  path: /export/dopyt
  controller: App\Controller\ExportController::dopyt
  options:
    hide_in_sitemap: true

export_ponuka:
  methods: GET
  path: /export/ponuka
  controller: App\Controller\ExportController::ponuka
  options:
    hide_in_sitemap: true

help_request:
  methods: GET|POST
  path: /ziadost-o-pomoc
  controller: App\Controller\HelpRequestController::index

help_request_success:
  methods: GET
  path: /ziadost-o-pomoc/dakujeme
  controller: App\Controller\HelpRequestController::success
  options:
    hide_in_sitemap: true

policy:
  methods: GET
  path: /pravidla-ochrany-osobnych-udajov
  controller: App\Controller\PolicyController::index

recipients:
  methods: GET
  path: /historia-pomoci
  controller: App\Controller\RecipientsController::index

speak-about-it:
  methods: GET
  path: /hovorme-o-tom
  controller: App\Controller\SpeakAboutItController::index

we-helped:
  methods: GET
  path: /komu-sme-pomohli
  controller: App\Controller\WeHelpedController::index

#
# Hidden from Sitemap
#
faq:
  methods: GET
  path: /faq
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  options:
    hide_in_sitemap: true
  defaults:
    route: about
    permanent: true

update_account_balance:
  methods: GET
  path: /update-account-balance/{cronToken}
  controller: App\Controller\UpdateAccountBalanceController::index
  options:
    hide_in_sitemap: true
  requirements:
    cronToken: ^[0-9a-zA-Z]{64}

sitemap:
  methods: GET
  path: /sitemap.{format}
  controller: App\Controller\SitemapController::index
  options:
    hide_in_sitemap: true
  requirements:
    format: xml

security_login:
  methods: GET|POST
  path: /login
  controller: App\Controller\SecurityController::login
  options:
    hide_in_sitemap: true

security_logout:
  methods: GET
  path: /logout
  controller: App\Controller\SecurityController::logout
  options:
    hide_in_sitemap: true

admin_download_donation_import_file:
  methods: GET
  path: '%app.path.user_contracts%/{id}'
  controller: App\Controller\Admin\DonationImportController::downloadImportAction
  options:
    hide_in_sitemap: true
  requirements:
    cronToken: '[0-9]+'

